
import static java.lang.Double.parseDouble;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOAS HOUSE
 */
public class Campeonato2023 extends javax.swing.JFrame {

    public Pilha p = new Pilha(200);
    public Queue f = new Queue(200);
    ArrayList<Atleta> atletas = new ArrayList<>();
    ArrayList<Double> listaBrasil = new ArrayList<>();
    ArrayList<Double> alturas = new ArrayList<>();

    
    public Campeonato2023() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnMediaGeral = new javax.swing.JButton();
        btnMulherAltura = new javax.swing.JButton();
        btnMediaHomens = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        btnMostrarPilha = new javax.swing.JButton();
        btnMostrarFila = new javax.swing.JButton();
        btnRetirarPilha = new javax.swing.JButton();
        btnRetirarFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campeonato 2023");

        jLabel1.setText("Nome do atleta:");

        jLabel2.setText("País:");

        jLabel3.setText("Sexo:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rbMasculino);
        rbMasculino.setText("Masculino");

        buttonGroup1.add(rbFeminino);
        rbFeminino.setSelected(true);
        rbFeminino.setText("Feminino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMasculino)
                .addGap(29, 29, 29))
        );

        jLabel4.setText("Altura:");

        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultados);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar Cadastro");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnMediaGeral.setText("Média geral");
        btnMediaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaGeralActionPerformed(evt);
            }
        });

        btnMulherAltura.setText("Mulher maior altura");
        btnMulherAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulherAlturaActionPerformed(evt);
            }
        });

        btnMediaHomens.setText("Média homens brasileiros");
        btnMediaHomens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaHomensActionPerformed(evt);
            }
        });

        btnAutores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAutores.setText("Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        btnMostrarPilha.setText("Mostrar pilha");
        btnMostrarPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPilhaActionPerformed(evt);
            }
        });

        btnMostrarFila.setText("Mostrar fila");
        btnMostrarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFilaActionPerformed(evt);
            }
        });

        btnRetirarPilha.setText("Retirar da pilha");
        btnRetirarPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarPilhaActionPerformed(evt);
            }
        });

        btnRetirarFila.setText("Retirar da fila");
        btnRetirarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarPilha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRetirarPilha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRetirarFila))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMediaGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMulherAltura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMediaHomens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAutores))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnListar)
                    .addComponent(btnMediaGeral)
                    .addComponent(btnMulherAltura)
                    .addComponent(btnMediaHomens)
                    .addComponent(btnAutores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarPilha)
                    .addComponent(btnMostrarFila)
                    .addComponent(btnRetirarPilha)
                    .addComponent(btnRetirarFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        txtAreaResultados.setText("Atletas" + atletas.toString() + "\n" + "\n" + "Mulheres" + p.toString() + "\n" + "\n" + "Homens" + f.toString());        
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnMulherAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulherAlturaActionPerformed
        Atleta atletaMaisAlta = null;
        double maiorAltura = 0;
        
        for(Atleta alta : atletas){
            if(alta.getAltura() > maiorAltura && alta.getSexo() == 'F'){
                atletaMaisAlta = alta;
                maiorAltura = alta.getAltura();
            }
        }
        
        txtAreaResultados.setText("A mulher mais alta é a " + atletaMaisAlta.getNome() + " com a altura de " + atletaMaisAlta.getAltura() + "m");
    }//GEN-LAST:event_btnMulherAlturaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            String nome = txtNome.getText();
            String pais = txtPais.getText();
            char osexo = 0;
            if(rbFeminino.isSelected()){
                osexo = 'F';
            }else if(rbMasculino.isSelected()){
                osexo = 'M';
            }
            double altura = parseDouble(txtAltura.getText());
            Atleta atl = new Atleta(nome, osexo, pais, altura);
            atletas.add(atl);
            alturas.add(altura);
            txtAreaResultados.setText("O atleta foi adicionado na lista!");
                        
            
            if(atl.getSexo() == 'F') {
                p.push(atl);
            }
            
            if(atl.getSexo() == 'M') {
                f.enqueue(atl);
            }
            
            if(pais.equals("Brasil") || pais.equals("brasil") && osexo == 'M'){
                listaBrasil.add(altura);
            }
            
            limparCampos();
                                      
        } catch (NumberFormatException erro) {
            txtAreaResultados.setText("Erro nos dados digitados!!!");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnMostrarPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPilhaActionPerformed
        if(!p.isEmpty()){
            txtAreaResultados.setText(p.toString());
        }else{
            txtAreaResultados.setText("A pilha está vazia.");
        }
    }//GEN-LAST:event_btnMostrarPilhaActionPerformed

    private void btnMostrarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFilaActionPerformed
        if(!f.isEmpty()){
            txtAreaResultados.setText(f.toString());
        }else{
            txtAreaResultados.setText("A fila está vazia.");
        }
    }//GEN-LAST:event_btnMostrarFilaActionPerformed

    private void btnRetirarPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarPilhaActionPerformed
        if(!p.isEmpty()){
            p.pop();
            txtAreaResultados.setText(p.toString());
        }else{
            txtAreaResultados.setText("Não é possível retirar, pois a pilha está vazia.");
        }
    }//GEN-LAST:event_btnRetirarPilhaActionPerformed

    private void btnRetirarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarFilaActionPerformed
        if(!f.isEmpty()){
            f.dequeue();
            txtAreaResultados.setText(f.toString());
        }else{
            txtAreaResultados.setText("Não é possível retirar, pois a fila está vazia.");
        }
    }//GEN-LAST:event_btnRetirarFilaActionPerformed

    private void btnMediaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaGeralActionPerformed
        double mediaGeral = 0;
        if(atletas.isEmpty()){
            txtAreaResultados.setText("Não há nenhum atleta cadastrado");
        }else{
            for(int i = 0; i < atletas.size(); i++){
                mediaGeral += alturas.get(i);
            }
            mediaGeral /= atletas.size();
        
            txtAreaResultados.setText("A média das alturas de todos os atletas é " + mediaGeral + "m");
        }
    }//GEN-LAST:event_btnMediaGeralActionPerformed

    private void btnMediaHomensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaHomensActionPerformed
        double mediaBrasil = 0;
        if(listaBrasil.isEmpty()){
            txtAreaResultados.setText("Não há nenhum atleta cadastrado");
        }else{
            for(int i = 0; i < listaBrasil.size(); i++){
                mediaBrasil += listaBrasil.get(i);
            }
            mediaBrasil /= listaBrasil.size();
        
            txtAreaResultados.setText("A média das alturas dos homens brasileiros é de " + mediaBrasil + "m");
        }
    }//GEN-LAST:event_btnMediaHomensActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        Sobre sob = new Sobre();
        sob.setVisible(true);
    }//GEN-LAST:event_btnAutoresActionPerformed

    public void limparCampos() {
        txtNome.setText("");
        txtPais.setText("");
        txtAltura.setText("");
        txtNome.requestFocus(); //para dar o foco ao 1º campo de texto
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Campeonato2023().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMediaGeral;
    private javax.swing.JButton btnMediaHomens;
    private javax.swing.JButton btnMostrarFila;
    private javax.swing.JButton btnMostrarPilha;
    private javax.swing.JButton btnMulherAltura;
    private javax.swing.JButton btnRetirarFila;
    private javax.swing.JButton btnRetirarPilha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextArea txtAreaResultados;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
