/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOAS HOUSE
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aluno7 = new javax.swing.JPanel();
        nome7 = new javax.swing.JLabel();
        rgm7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aluno9 = new javax.swing.JPanel();
        nome9 = new javax.swing.JLabel();
        rgm9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aluno6 = new javax.swing.JPanel();
        nome6 = new javax.swing.JLabel();
        rgm6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aluno8 = new javax.swing.JPanel();
        nome8 = new javax.swing.JLabel();
        rgm8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aluno10 = new javax.swing.JPanel();
        nome10 = new javax.swing.JLabel();
        rgm10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aluno11 = new javax.swing.JPanel();
        nome11 = new javax.swing.JLabel();
        rgm11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aluno12 = new javax.swing.JPanel();
        nome12 = new javax.swing.JLabel();
        rgm12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        aluno7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome7.setText("Aiyumi Karen Tamada");
        nome7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm7.setText("30213673");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karen.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        aluno9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome9.setText("Aiyumi Karen Tamada");
        nome9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm9.setText("30213673");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karen.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno9Layout = new javax.swing.GroupLayout(aluno9);
        aluno9.setLayout(aluno9Layout);
        aluno9Layout.setHorizontalGroup(
            aluno9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno9Layout.createSequentialGroup()
                .addGroup(aluno9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno9Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(nome9))
                    .addGroup(aluno9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno9Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(rgm9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        aluno9Layout.setVerticalGroup(
            aluno9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aluno7Layout = new javax.swing.GroupLayout(aluno7);
        aluno7.setLayout(aluno7Layout);
        aluno7Layout.setHorizontalGroup(
            aluno7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno7Layout.createSequentialGroup()
                .addGroup(aluno7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno7Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(nome7))
                    .addGroup(aluno7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno7Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(rgm7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(aluno7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aluno7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(aluno9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        aluno7Layout.setVerticalGroup(
            aluno7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(aluno7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aluno7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(aluno9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setTitle("Autores");

        aluno6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome6.setText("Aiyumi Karen Tamada");
        nome6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm6.setText("30213673");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karen.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno6Layout = new javax.swing.GroupLayout(aluno6);
        aluno6.setLayout(aluno6Layout);
        aluno6Layout.setHorizontalGroup(
            aluno6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno6Layout.createSequentialGroup()
                .addGroup(aluno6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno6Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(nome6))
                    .addGroup(aluno6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno6Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(rgm6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        aluno6Layout.setVerticalGroup(
            aluno6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aluno8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome8.setText("Andressa Cateano");
        nome8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm8.setText("31864830");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/andressa.jpeg"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno8Layout = new javax.swing.GroupLayout(aluno8);
        aluno8.setLayout(aluno8Layout);
        aluno8Layout.setHorizontalGroup(
            aluno8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno8Layout.createSequentialGroup()
                .addGroup(aluno8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno8Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(nome8)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluno8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rgm8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        aluno8Layout.setVerticalGroup(
            aluno8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aluno10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome10.setText("Julia Boaventura");
        nome10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm10.setText("29440254");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/julia2.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno10Layout = new javax.swing.GroupLayout(aluno10);
        aluno10.setLayout(aluno10Layout);
        aluno10Layout.setHorizontalGroup(
            aluno10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno10Layout.createSequentialGroup()
                .addGroup(aluno10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno10Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(rgm10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluno10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nome10)
                .addGap(77, 77, 77))
        );
        aluno10Layout.setVerticalGroup(
            aluno10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        aluno11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome11.setText("Uriel Vieira");
        nome11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm11.setText("29619602");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uriel.jpeg"))); // NOI18N
        jLabel7.setText("jLabel1");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno11Layout = new javax.swing.GroupLayout(aluno11);
        aluno11.setLayout(aluno11Layout);
        aluno11Layout.setHorizontalGroup(
            aluno11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno11Layout.createSequentialGroup()
                .addGroup(aluno11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aluno11Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aluno11Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(nome11)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluno11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rgm11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        aluno11Layout.setVerticalGroup(
            aluno11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        aluno12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nome12.setText("Thainara Andrade");
        nome12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rgm12.setText("30123224");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thainara.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout aluno12Layout = new javax.swing.GroupLayout(aluno12);
        aluno12.setLayout(aluno12Layout);
        aluno12Layout.setHorizontalGroup(
            aluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluno12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nome12)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aluno12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rgm12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        aluno12Layout.setVerticalGroup(
            aluno12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluno12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nome12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rgm12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aluno11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aluno6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aluno8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aluno12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(aluno10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aluno10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aluno6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aluno8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aluno11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aluno12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aluno10;
    private javax.swing.JPanel aluno11;
    private javax.swing.JPanel aluno12;
    private javax.swing.JPanel aluno6;
    private javax.swing.JPanel aluno7;
    private javax.swing.JPanel aluno8;
    private javax.swing.JPanel aluno9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nome10;
    private javax.swing.JLabel nome11;
    private javax.swing.JLabel nome12;
    private javax.swing.JLabel nome6;
    private javax.swing.JLabel nome7;
    private javax.swing.JLabel nome8;
    private javax.swing.JLabel nome9;
    private javax.swing.JLabel rgm10;
    private javax.swing.JLabel rgm11;
    private javax.swing.JLabel rgm12;
    private javax.swing.JLabel rgm6;
    private javax.swing.JLabel rgm7;
    private javax.swing.JLabel rgm8;
    private javax.swing.JLabel rgm9;
    // End of variables declaration//GEN-END:variables
}
